spring.application.name=nxt-trendz-backend

# MySQL
spring.datasource.url=jdbc:mysql://nxt-trendz-db-natinavasu9-4e4.a.aivencloud.com:28951/defaultdb?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=NxtTrendzSuperSecretKeyForJWTTokenSigningMustBe256BitsLong123456
jwt.expiration=86400000

# Server
server.port=8088

# CORS
spring.web.cors.allowed-origins=http://localhost:5173
